import argparse
import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.data import build_dataset, inverse_target
from src.link_adaptation import build_adaptation_table, compute_turbulence_thresholds, summarize_adaptation_table
from src.utils.config import load_config


def parse_args():
    parser = argparse.ArgumentParser(description="Generate a star-ground link adaptation report from turbulence forecasts.")
    parser.add_argument("--config", required=True, help="Config used to rebuild the dataset and derive calibration thresholds.")
    parser.add_argument("--predictions-csv", required=True, help="Predictions CSV generated by an experiment output.")
    parser.add_argument("--output-dir", required=True, help="Directory to save link adaptation artifacts.")
    parser.add_argument(
        "--prediction-prefix",
        default=None,
        help="Prediction prefix without horizon suffix, e.g. meta_fusion_pred. Auto-detect when omitted.",
    )
    return parser.parse_args()


def infer_prediction_prefix(pred_df: pd.DataFrame) -> str:
    candidates = sorted([col[:-3] for col in pred_df.columns if col.endswith("_h1") and "_pred" in col])
    if not candidates:
        raise ValueError("Could not auto-detect a prediction prefix from the CSV.")
    preferred_order = ["meta_fusion_pred", "fusion_main_pred"]
    for candidate in preferred_order:
        if candidate in candidates:
            return candidate
    return candidates[0]


def main():
    args = parse_args()
    cfg_path = Path(args.config)
    if not cfg_path.is_absolute():
        cfg_path = (ROOT / cfg_path).resolve()
    cfg = load_config(str(cfg_path))

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    pred_df = pd.read_csv(args.predictions_csv)
    pred_prefix = args.prediction_prefix or infer_prediction_prefix(pred_df)

    ds = build_dataset(cfg)
    y_train_inv = inverse_target(ds["y_train_abs"], ds["scaler"], ds["target_idx"], ds["feature_count"])
    thresholds = compute_turbulence_thresholds(y_train_inv[:, 0])

    adaptation_df = build_adaptation_table(pred_df, pred_prefix=pred_prefix, thresholds=thresholds)
    summary = summarize_adaptation_table(adaptation_df, thresholds=thresholds, pred_prefix=pred_prefix)

    adaptation_df.to_csv(output_dir / "link_adaptation_plan.csv", index=False, encoding="utf-8-sig")
    (output_dir / "link_adaptation_summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

    md_lines = [
        "# Star-Ground Link Adaptation Report",
        "",
        f"- Prediction source: `{args.predictions_csv}`",
        f"- Prediction prefix: `{pred_prefix}`",
        f"- Rows analyzed: `{summary['rows']}`",
        "",
        "## Turbulence Thresholds",
        "",
        f"- good_max: `{thresholds['good_max']:.6f}`",
        f"- watch_max: `{thresholds['watch_max']:.6f}`",
        f"- degraded_max: `{thresholds['degraded_max']:.6f}`",
        "",
        "## Level Counts",
        "",
    ]
    for level, count in summary["level_counts"].items():
        md_lines.append(f"- {level}: `{count}`")
    md_lines += [
        "",
        "## Interpretation",
        "",
        "- The forecast uses the worst predicted LogCn2 over the next three steps as the short-horizon risk proxy.",
        "- Higher LogCn2 means stronger turbulence and therefore a more conservative communication action profile.",
        "- Satellite azimuth/elevation are not freely changed by the controller; in practice the adaptive part is pointing compensation, tracking gain, reacquisition policy, and optional site/channel handover.",
        "",
        "## Artifacts",
        "",
        f"- Plan CSV: `{output_dir / 'link_adaptation_plan.csv'}`",
        f"- Summary JSON: `{output_dir / 'link_adaptation_summary.json'}`",
    ]
    (output_dir / "link_adaptation_report.md").write_text("\n".join(md_lines), encoding="utf-8")

    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
